### ISSUE TITLE
Ubuntu/Debian integration

### ISSUE THREAD

**Issue by fragtion** [arco/linux-amlogic#1]
Hi, I was able to compile most of the kernel parts, but at "LD init/built-in.o" stage it seemed to all go wrong. Copy of the log is on pastebin at http://pastebin.com/xyYsQaXr . Please help

**Comment by arco** [comment]
Hey.

The kernel is originally meant to be compiled as part of OpenELEC or
LibreELEC. You can try copying

https://github.com/arco/LibreELEC.tv/blob/libreelec-7.0/projects/MK809_Plus/linux/linux.arm.conf

to arch/arm/configs and rename it to for example amlogic_defconfig
Then do

make amlogic_defconfig
ARCH=arm make

**Comment by fragtion** [comment]
Hey arco, thanks for quick response & for all your hard work that has gone into this repo

That makes a lot of sense. I have followed your advice, but my device is meson6 (aml8726-mx) g18ref-newmtd, so after downloading the suggested conf, I changed CONFIG_BUILD_ARM_APPENDED_DTB_IMAGE_NAMES and similar entries to reflect meson6_g18. and then corrected some dependency errors as needed while building

Compilation seems to have been successful eventually, but is now failing at make dtbs:

```
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
make[1]: 'include/generated/mach-types.h' is up to date.
  CALL    scripts/checksyscalls.sh
  CC      scripts/mod/devicetable-offsets.s
  GEN     scripts/mod/devicetable-offsets.h
  HOSTCC  scripts/mod/file2alias.o
  HOSTLD  scripts/mod/modpost
  CHK     include/generated/compile.h
  CHK     kernel/config_data.h
  Kernel: arch/arm/boot/Image is ready
  Kernel: arch/arm/boot/zImage is ready
  DTC     arch/arm/boot/dts/amlogic/meson6_g18.dtb
  CAT     arch/arm/boot/zImage-dtb
  Kernel: arch/arm/boot/zImage-dtb is ready
scripts/Makefile.build:128: kbuild: Makefile.build is included improperly
make[1]: *** No rule to make target 'dtbs'.  Stop.
/usr/cache1/kernel/build/linux-amlogic/arch/arm/Makefile:318: recipe for target 'dtbs' failed
make: *** [dtbs] Error 2
```
Any suggestions? ;)

**Comment by arco** [comment]
Ah yeah, I've never really compiled the kernel outside of the LibreELEC
environment. It compiles the kernel automatically as part of the build
process, and makes an Android bootimage. I think you need to do something
like this:

ARCH=arm make uImage
ARCH=arm make meson8b_mk809plus.dtd
ARCH=arm make meson8b_mk809plus.dtb

**Comment by fragtion** [comment]
OK, that worked... Well, kind of... Some problems booting the built kernel now ;/

```
m6_mbx_v1#setenv bootargs "root=/dev/data rw rootfstype=ext4 rootwait init=/init rdinit=/init console=ttyS0,115200n8 mac=c4:4e:ac:07:c0:0c logo=osd1,0x84100000,720p,full androidboot.resolution=720p nohlt vmalloc=256m mem=1024m a9_clk_max=1512000000 boot=/dev/system disk=/dev/data BOOT_IMAGE=/dev/mtd4 console=tty0 consoleblank=0 scaling_governor=hotplug scaling_min_freq=200000 scaling_max_freq=1152000 systemd.show_status=auto"
m6_mbx_v1#run mmcargs;if mmcinfo; then if fatload mmc 0 0x82000000 uImage; then bootm;fi;fi;
## Error: "mmcargs" not defined
 sdio_detect return 1
Device: SDIO Port B
Manufacturer ID: 0
OEM: 0
Name: tTran Speed: 40000000
Rd Block Len: 512
SD version 2.0
High Capacity: Yes
Capacity: 64490569728
Boot Part Size: 0
Bus Width: 4-bit
reading uImage

4649144 bytes read
## Booting kernel from Legacy Image at 82000000 ...
   Image Name:
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    4649080 Bytes = 4.4 MiB
   Load Address: 00000000
   Entry Point:  00000000
   Verifying Checksum ... OK
   XIP Kernel Image ... OK
OK
machid from environment: 0x4e27
EFUSE machid is not set.
Using machid 0x4e27 from environment

Starting kernel ...
▒EEEE I3000000032940xf300110303;77520EEEE I400000004294_M6_BL1_3431>2534313
TE : 92347
wait pll-0x03 target is 0204 now it is 0x00000203

DDR clock is 516MHz with Low Power & 1T mode

DDR training :
DX0DLLCR:40000000
DX0DQTR:ffffffff
DX0DQSTR:3db05001
DX1DLLCR:40000000
DX1DQTR:ffffffff
DX1DQSTR:3db05001
DX2DLLCR:40000000
DX2DQTR:ffffffff
DX2DQSTR:3db05001
DX3DLLCR:40000000
DX3DQTR:ffffffff
DX3DQSTR:3db05001
```
What would be the most likely causes of this? Wrong dtd/dts/mtd settings maybe? Is there a device tree file for G18REF_NEWMTD?

Thanks in advance for any additional feedback

**Comment by arco** [comment]
There's some generic meson6 dtd files in arch/arm/boot/dts/amlogic/
It should also be possible to extract it it you have a stock Android bootimage for your device.
Also, my defconfig is set up for meson8b, so you probably need to modify it for meson6.

**Comment by fragtion** [comment]
Brilliant I just got 3.10.102 to compile and boot :) The key was to use a config file generated by the project on codesnake's amlogic openelec repo. Not sure which variable it was that was hanging the kernel start but just glad it's working now!!
